name: KOK-JDC-AX1800-PRO-IPQ60XX-6.12-WIFI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 6

jobs:
  build:
    uses: ./.github/workflows/build-openwrt.yml
    secrets: inherit
    with:
      repo_url: "https://github.com/King-Of-Knights/openwrt-6.x"
      repo_branch: "main"
      config_file: "configs/jdc-ax1800-pro.config"
      diy_script: "libwrt.sh"
      firmware_tag: "KoK-JDC-AX1800-PRO-IPQ60XX-6.12-WIFI"
      firmware_description: "6.12 kernel firmware with WIFI + Wired NSS support (King-Of-Knights fork)"
      install_extra_packages: true
      kernel_version_file: "kernel-6.12"
